# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: cmdr-nova@internet:~$
home: NOVA PRIME
email: cmdr-nova@mkultra.monster
timezone: America/New_York
description: >- # this means to ignore newlines until "baseurl:"
  cmdr-nova's personal blog and home on the indie-web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mkultra.monster" # the base hostname & protocol for your site, e.g. http://example.com
lang: "en-US"
github_username:  cmdr-nova
mastodon:
- username: daemon_nova
  instance: labyrinth.zone

# Build settings
theme: minima
plugins_dir: _plugins

plugins:
  - jekyll-feed
  - jekyll-paginate 
  - jekyll-compose
  - jekyll-compress-images

paginate: 7
paginate_path: "/page:num/"

future: true

compress_images:
  images_path: "/img/**/*.{gif,png,jpg,jpeg,svg}"

collections:
  notes:
    output: true
    permalink: /notes/:year/:month/:day/:title/
  posts:
    output: true
  logs:
    output: true
    permalink: /logs/:year/:month/:day/:title/

tag_categories:
  tech:
    - linux
    - webdev
    - programming
    - webdev
    - tech
    - scripting
    - python
    - jekyll
    - github
    - computing
    - htaccess
    - javascript
    - tags
    - modding
    - html
    - terminal
    - startup
    - robots
    - nvidia
    - internet
    - install
    - blockai
    - block
  projects:
    - release
  lifestyle:
    - travel
    - food
    - health
    - ramen
  nature:
    - space
  gaming:
    - gaming
    - gamingnews
    - blizzard
    - sims4
    - thewitcher4
    - thesims2
    - diablo4
    - kingdom-come
    - javascript-game
    - masseffectandromeda
    - intergalactic
    - anticheat
  metaverse:
    - second-life
    - secondlife
    - vr-chat
    - virtualworld
    - lindenlabs
    - stores
    - products
    - revosa
    - metaverse
    - firestorm
  social media:
    - activitypub
    - mastodon
    - akkoma
    - bluesky
    - threads
    - twitter
    - instagram
    - social-media
    - socialmedia
    - meta
    - facebook
    - reddit
    - sharkey
    - fediverse
    - tumblr
    - lemmy
    - pixelfed
    - wafrn
    - tiktokban
    - toxicity
    - migration
    - banned
  call to action:
    - donations
  politics:
    - oligarchy
    - bechdel
    - bechdel-test
    - bechdeltest
    - lgbtq+
    - lgbtq
    - uhc
    - deny
    - defend
    - depose
    - climatechange
    - politics
    - gamergate
    - ai
    - controversy
  television:
    - dexter
    - television
    - media
    - tv
  media:
    - backrooms
    - thebackrooms
  expression:
    - writing
    - thoughts
    - writing-prompt
    - quiz
    - questions
    - blogging
    - indieweb
    - image
    - creators
    - aging
    - writer
    - work
    - webmaster
    - waybackmachine
    - rich
    - oldnet
    - ode
    - nineties
    - not
    - newyear
    - inspiration
    - happen
    - gonna
    - famous
    - challenge
  writing:
    - fiction
  music: 
    - music
    - spotify
    - wrapped
    - numetal
    - orgy
    - streaming
  logging:
    - updates
    - website
    - comments
    - testing
    - test
    - design
    - consolidate
  help:
    - tutorials
  # Add more categories and tags as needed

# New fields not defaulted by jekyll-new with the minima theme
# Add a copyright. A copyright symbol and year will be added automatically
# copyright: Company Name, Inc. 
#copyright: "Commander Nova"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
