baseurl: ''
collections:
  hacker-toots:
    output: true
    permalink: /hacker-toots/:path/
  logs:
    output: true
    permalink: /logs/:year/:month/:day/:title/
  notes:
    output: true
    permalink: /notes/:year/:month/:day/:title/
  posts:
    output: true
  skeets:
    output: true
    permalink: /skeets/:path/
  submissions:
    output: true
    permalink: /submissions/:path/
  texts:
    output: true
    permalink: /texts/:path/
  toots:
    output: true
    permalink: /toots/:path/
compress_images:
  images_path: /img/**/*.{gif,png,jpg,jpeg,svg}
description: cmdr-nova's personal blog and home on the indie-web.
email: cmdr-nova@mkultra.monster
future: true
github_username: cmdr-nova
home: NOVA PRIME
lang: en-US
mastodon:
- instance: mastodon.online
  username: cmdr_nova
pagination:
  enabled: true
  limit: 0
  per_page: 10
  sort_field: date
  sort_reverse: true
  title: :title - page :num
  trail:
    after: 2
    before: 2
plugins:
- jekyll-feed
- jekyll-paginate-v2
- jekyll-compose
- jekyll-compress-images
- jekyll-tagging
plugins_dir: _plugins
tag_categories:
  call to action:
  - donations
  expression:
  - writing
  - thoughts
  - shitpost
  - writing-prompt
  - quiz
  - questions
  - blogging
  - indieweb
  - image
  - creators
  - aging
  - writer
  - work
  - webmaster
  - waybackmachine
  - rich
  - oldnet
  - ode
  - nineties
  - not
  - newyear
  - inspiration
  - happen
  - gonna
  - famous
  - challenge
  gaming:
  - gaming
  - gamingnews
  - blizzard
  - sims4
  - thewitcher4
  - thesims2
  - diablo4
  - kingdom-come
  - javascript-game
  - masseffectandromeda
  - intergalactic
  - anticheat
  help:
  - tutorials
  lifestyle:
  - travel
  - food
  - health
  - ramen
  logging:
  - updates
  - website
  - comments
  - testing
  - test
  - design
  - consolidate
  media:
  - backrooms
  - thebackrooms
  metaverse:
  - second-life
  - secondlife
  - vr-chat
  - virtualworld
  - lindenlabs
  - stores
  - products
  - revosa
  - metaverse
  - firestorm
  music:
  - music
  - spotify
  - wrapped
  - numetal
  - orgy
  - streaming
  nature:
  - space
  politics:
  - oligarchy
  - bechdel
  - bechdel-test
  - bechdeltest
  - lgbtq+
  - lgbtq
  - uhc
  - deny
  - defend
  - depose
  - climatechange
  - politics
  - gamergate
  - ai
  - controversy
  projects:
  - release
  - eyeshadow2600fm
  social media:
  - activitypub
  - mastodon
  - akkoma
  - bluesky
  - threads
  - twitter
  - instagram
  - social-media
  - socialmedia
  - pillowfort
  - meta
  - facebook
  - reddit
  - sharkey
  - fediverse
  - tik tok
  - tumblr
  - lemmy
  - pixelfed
  - wafrn
  - tiktokban
  - toxicity
  - migration
  - banned
  tech:
  - linux
  - webdev
  - programming
  - tech
  - scripting
  - python
  - jekyll
  - github
  - computing
  - htaccess
  - javascript
  - tags
  - modding
  - html
  - terminal
  - startup
  - robots
  - nvidia
  - internet
  - install
  - blockai
  - block
  television:
  - dexter
  - television
  - media
  - tv
  uncategorized:
  - ''
  - blog
  - oof
  - label
  - coffee
  - bread
  - firefox
  - mutuals
  - post
  - scrapers
  - css
  - indexing
  - grave
  - posting
  - scams
  - cyberpunk
  - eora
  - mozilla
  - world-of-warcraft
  - kingdomcome2
  - baby
  - avowed
  - overhaul
  - sad
  - thinking
  - syndication
  - life
  - pandora
  - night
  - amongus
  - update
  - cats
  - app
  - mac
  - java
  - nuggets
  - bots
  - second
  - sleep
  - rss
  - note
  - patreon
  - neo-machina
  - littledudes
  - guidwars2
  - share-links
  - log
  - pillars-of-eternity
  - international-womens-day
  writing:
  - fiction
theme: minima
timezone: America/New_York
title: cmdr-nova@internet:~$
url: https://mkultra.monster
