name: Deploy to Neocities and Post to Mastodon

on:
  push:
    branches:
      - master

concurrency: # Prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Bundler
      run: gem install bundler -v 2.4.22

    - name: Install dependencies
      run: bundle install

    - name: Build static site
      run: bundle exec jekyll build

    - name: List _site directory
      run: ls -la _site

    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v2.0.2
      with:
        api_token: ${{ secrets.NEOCITIES_API_KEY }} # Uses API key from Neocities
        cleanup: false
        dist_dir: _site

    - name: Check for new posts
      id: check_new_posts
      run: |
        new_post=false
        previous_commit=$(git rev-parse HEAD~1 || echo "")
        if [ -n "$previous_commit" ]; then
          for file in $(git diff --name-only $previous_commit HEAD); do
            if [[ $file == _posts/* ]]; then
              if [[ $(git log --diff-filter=A --follow --format=%aD -1 -- $file) == $(date -R) ]]; then
                new_post=true
                break
              fi
            fi
          done
        fi
        echo "new_post=$new_post" >> $GITHUB_ENV
        echo "new_post=$new_post" >> $GITHUB_OUTPUT

    - name: Post to Mastodon
      if: env.new_post == 'true'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        MASTODON_API_KEY: ${{ secrets.MASTODON_API_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no root@67.205.188.225 'MASTODON_API_KEY=${{ secrets.MASTODON_API_KEY }} python3 /masto-poast/poast.py "New post published: ${{ github.event.head_commit.message }}"'