# this is a file that will automatically push commits to your neocities webpage. by creating a repository secret with your neocities api token, and then specifying which directory to use at the bottom, you no longer need to use FTP apps and you can keep a mirror of your site that updates in realtime alongside the neocities version.

name: Deploy to neocities

# only run on changes to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # When the dist_dir is ready, deploy it to neocities
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          dist_dir: cmdr-nova.github.io